<<<<<<< HEAD
---
server:
  port: 8080
  contextPath: /bns
---
spring:
  profiles: local, default
  messages:
    basename: validation
security:
  ignored:
    - "*.bundle.*"
      
datasource:
  bns:
    url: jdbc:h2:~/bns
    username: BNS_APP
    password: password1
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  
---
spring:
  profiles: prod
  messages:
    basename: validation
security:
  ignored:
    - "*.bundle.*"   
    
datasource:
  bns:
    url: jdbc:mysql://localhost:3306/BNS_DB
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

=======
---
server:
  port: 8080
  contextPath: /bns
---
spring:
  profiles: local, default
  messages:
    basename: validation
security:
  ignored:
    - "*.bundle.*"
      
datasource:
  bns:
    url: jdbc:h2:~/bns
    username: BNS_APP
    password: password1
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  
---
spring:
  profiles: prod
  messages:
    basename: validation
security:
  ignored:
    - "*.bundle.*"   
    
datasource:
  bns:
    url: jdbc:mysql://localhost:3306/BNS_DB
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: beta
  messages:
    basename: validation
security:
  ignored:
    - "*.bundle.*"

datasource:
  bns:
    url: jdbc:mysql://localhost:3306/bns_db
    username: bns_db
    password: ka8TfnZJRrFYtDwY
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

>>>>>>> e379995e7a0877d83b0daeb29bedfdf39e05bf91
