---
server:
  port: 8080
  servlet:
    contextPath: /bns
spring:
  messages:
    basename: validation
  security:
    ignored:
      - "*.bundle.*"
  cloud:
    discovery:
      enabled: false
eureka:
  instance:
    registerWithEureka: false
  client:
    enabled: false

---
spring:
  profiles: local, default

datasource:
  bns:
    url: "jdbc:h2:~/bns"
    username: BNS_APP
    password: password1
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: prod

datasource:
  bns:
    url: "jdbc:mysql://10.125.128.18:3306/bns_db"
    username: bns
    password: bns
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: beta
datasource:
  bns:
    url: jdbc:mysql://localhost:3306/bns_db
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
